36.03 wrap space in group
exo-addons/functional-configuration pull request #19
Opened 2020-01-14 10:27 UTC by slickexo2

Add group to manage spaces.

This PR contains :

Functional confguration administration. Admin is able to manage group for space
Portlet (view+edit) to manage navigation portlet

2020-01-15 14:03 UTC, thomasdelhomenie requested changes

2020-01-15 14:03 UTC, thomasdelhomenie commented on portlets/src/main/frontend/apps/hightLightSpaces/edit/HighlightSpacesEdit.js
> +import axios from 'axios';
Is axios really necessary ? It seems all the http calls can be done with the native fetch API.

2020-01-15 14:03 UTC, thomasdelhomenie commented on portlets/src/main/frontend/apps/hightLightSpaces/view/components/HighlightSpacesView.vue
> +        <span style="color: #ffffff;padding-left:15px;font-weight:bold;">{{$root.portletName}}</span>
Style must be moved in the style section.

2020-01-15 14:03 UTC, thomasdelhomenie commented on portlets/src/main/frontend/apps/hightLightSpaces/edit/components/HighlightSpacesEdit.vue
> +            console.log(spaceConfigurations);
To remove.

2020-01-15 14:03 UTC, thomasdelhomenie commented on portlets/src/main/frontend/apps/hightLightSpaces/edit/components/HighlightSpacesEdit.vue
> +            <label class="control-label" for="portlet_name">Nom de la portlet : </label>
Please internationalize all labels.

2020-01-15 14:03 UTC, thomasdelhomenie commented on portlets/src/main/frontend/apps/hightLightSpaces/edit/components/HighlightSpacesEdit.vue
> +            <input type="button" class="btn" value="Fermer" onclick="javascript:eXo.webui.UIForm.submitForm('UIPortletForm','Close',true)"/>
There is no need for a Close button in the edit page I think since there is already a close button in the main popup.

2020-01-15 14:03 UTC, thomasdelhomenie commented on portlets/src/main/webapp/WEB-INF/portlet.xml
> +			<title>Spaces group</title>
```suggestion
			<title>Highlighted spaces group</title>
```

2020-01-15 14:03 UTC, thomasdelhomenie commented on portlets/src/main/webapp/WEB-INF/portlet.xml
> +		<display-name>Highlight spaces portlet</display-name>
```suggestion
		<display-name>Highlighted spaces portlet</display-name>
```

2020-01-15 14:03 UTC, thomasdelhomenie commented on portlets/src/main/webapp/WEB-INF/portlet.xml
> +			<keywords>Spaces group</keywords>
```suggestion
			<keywords>Highlighted spaces group</keywords>
```

2020-01-15 14:03 UTC, thomasdelhomenie commented on service/src/main/java/org/exoplatform/highlight/spaces/HighlightSpacesService.java
> +    return highlightSpaces;//.stream().map(HighlightSpace::getSpace).collect(Collectors.toList());
Remove comment if not useful.

2020-01-15 14:03 UTC, thomasdelhomenie commented on service/src/main/java/org/exoplatform/rest/FunctionalConfigurationController.java
> +    @RolesAllowed("administrators")
Should be "users" to make it accessible to all users.

2020-01-17 08:33 UTC, slickexo2 commented on portlets/src/main/frontend/apps/hightLightSpaces/edit/HighlightSpacesEdit.js
> +import axios from 'axios';
Fetch API is not compatible for all browsers. Axios is already used for backend calls and to standardize calls we preferred to use axios. But we can change if you prefer ?

2020-01-17 11:06 UTC, thomasdelhomenie commented on portlets/src/main/frontend/apps/hightLightSpaces/edit/HighlightSpacesEdit.js
> +import axios from 'axios';
Fetch is supported in all browsers we support : https://caniuse.com/#feat=fetch . So we can use it to avoid importing axios.

2020-01-20 09:22 UTC, thomasdelhomenie approved these changes

2020-01-20 18:38 UTC, merged