activity composer link in dropdown admin menu
exo-addons/functional-configuration pull request #2
Opened 2019-08-23 11:29 UTC by slickexo2

2019-08-26 07:03 UTC, rdenarie requested changes
Hello,
Please can you update labels and configuration file name to be homogeneous ?

Thanks !

2019-08-26 07:03 UTC, rdenarie commented on war/src/main/webapp/WEB-INF/conf/activity-composer-configuration/portal/setup-navigation.xml
> +            <uri>functional-composer</uri>
```suggestion
            <uri>functional-configuration</uri>
```

2019-08-26 07:03 UTC, rdenarie commented on war/src/main/webapp/WEB-INF/conf/activity-composer-configuration/portal/setup-navigation.xml
> +            <name>functional-composer</name>
```suggestion
            <name>functional-configuration</name>
```

2019-08-26 07:03 UTC, rdenarie commented on war/src/main/webapp/WEB-INF/conf/activity-composer-configuration/portal/setup-navigation.xml
> +            <label>Functional Composer</label>
```suggestion
            <label>Functional Configuration</label>
```

2019-08-26 07:03 UTC, rdenarie commented on war/src/main/webapp/WEB-INF/conf/activity-composer-configuration/portal/setup-navigation.xml
> +            <label xml:lang="en">Functional Composer</label>
```suggestion
            <label xml:lang="en">Functional Configuration</label>
```

2019-08-26 07:03 UTC, rdenarie commented on war/src/main/webapp/WEB-INF/conf/activity-composer-configuration/portal/setup-navigation.xml
> +            <label xml:lang="fr">Functional Composer</label>
```suggestion
            <label xml:lang="fr">Functional Configuration</label>
```

2019-08-26 07:03 UTC, rdenarie commented on war/src/main/webapp/WEB-INF/conf/activity-composer-configuration/menu-configuration.xml
> +                    <value>war:/conf/activity-composer-configuration/portal/setup-navigation.xml</value>
```suggestion
                    <value>war:/conf/functional-configuration/portal/setup-navigation.xml</value>
```
We should rename the file with the new name of the addon.

2019-09-13 14:38 UTC, rdenarie commented
@jpbriand I think we can close this PR as it is merged in the global one.
Can you confirm ?
Thx

2019-09-16 07:18 UTC, slickexo2 commented
@rdenarie  You can close this PR.
All the corrections are present in the other one.

2019-09-16 07:23 UTC, closed without merging